SocialStream::Presence.setup do |config| 
  #Configures Web Server Domain served by XMPP Server
config.domain = "localhost"
#Configures Bosh Service Path
#config.bosh_service = "http://xmpp-proxy/http-bind"
#Configures Authentication Method: "cookie" or "password"
config.auth_method = "cookie"
#Configures XMPP Server Password
config.xmpp_server_password = "autogenerated random password"
#Uncomment to enable REST API Security
#config.secure_rest_api = true
#Remote or local mode
config.remote_xmpp_server = false
#Scripts path to execute ejabberd scripts: local or remote
config.scripts_path = "/scripts_path"
#Ejabberd module path in the xmpp server
config.ejabberd_module_path = "/usr/lib/ejabberd/ebin"
#Uncomment to enable Social Stream Presence
#config.enable = true
end